// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInkmyhcO2YAuIZYJNdgPgW_8W0xRBOeA',
    appId: '1:597088342040:web:eb9cc091c567a1c133b36d',
    messagingSenderId: '597088342040',
    projectId: 'login-20603',
    authDomain: 'login-20603.firebaseapp.com',
    storageBucket: 'login-20603.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSOfZ9OuU_rZiG9CDtvvNSfTB9P_o9x5A',
    appId: '1:597088342040:android:7047b75a49f3acbb33b36d',
    messagingSenderId: '597088342040',
    projectId: 'login-20603',
    storageBucket: 'login-20603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGUIsRmCsdE7fpMZkphRnaVLE4WdOIQDs',
    appId: '1:597088342040:ios:cbd08f0ac29038bc33b36d',
    messagingSenderId: '597088342040',
    projectId: 'login-20603',
    storageBucket: 'login-20603.appspot.com',
    iosBundleId: 'com.example.prak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGUIsRmCsdE7fpMZkphRnaVLE4WdOIQDs',
    appId: '1:597088342040:ios:f904076f6c20190633b36d',
    messagingSenderId: '597088342040',
    projectId: 'login-20603',
    storageBucket: 'login-20603.appspot.com',
    iosBundleId: 'com.example.prak.RunnerTests',
  );
}
